obiba/mica-drupal7

drupal/modules/mica_client/mica_client_commons/includes/mica_client.inc
drupal/modules/mica_client/mica_client_facet_search/includes/mica_client_facet_search_resource.inc
drupal/modules/mica_client/mica_client_facet_search/includes/mica_client_facet_search_resource_facet_conf.inc

Search optimization:
* do not refresh aggregation on empty result
fix:
* fix js error on autocomplete when there are no matches

Search optimization

---

drupal/modules/mica_client/mica_client_dataset/templates/mica_client_dataset-detail.tpl.php
drupal/modules/mica_client/mica_client_dataset/templates/mica_client_variable-detail.tpl.php
drupal/modules/mica_client/mica_client_network/templates/mica_client_network-detail.tpl.php
drupal/modules/mica_client/mica_client_study/mica_client_study-page-detail.inc
drupal/modules/mica_client/mica_client_study/templates/mica_client_study-dce-detail.tpl.php
drupal/modules/mica_client/mica_client_study/templates/mica_client_study-detail.tpl.php
drupal/modules/mica_client/mica_client_study/templates/mica_client_study-population-detail.tpl.php
drupal/themes/micado_bootstrap/bootstrap/less/mixins/grid-framework.less
drupal/themes/micado_bootstrap/css/style.css

Debug tabs and modal navigation in study detail page
sections alignment in study, network, dataset, variable detail page

Responsive sm xs

---

drupal/modules/obiba_mica/obiba_mica_facet_search/includes/obiba_mica_facet_search_resource.inc
drupal/modules/obiba_mica/obiba_mica_network/obiba_mica_network-page-detail.inc
drupal/modules/obiba_mica/obiba_mica_network/templates/obiba_mica_network-detail.tpl.php

Made sure that group-by something else still works.

MK-209 Defaults to group by study id if not specified in the query

---

drupal/modules/obiba_mica/obiba_mica_commons/includes/obiba_mica.inc
drupal/modules/obiba_mica/obiba_mica_search/includes/obiba_mica_search_resource_facet_conf.inc

But still not satisfying as count is a variable count...

MK-244 Some facets moved from variables tab to studies tab

---

drupal/modules/obiba_mica/obiba_mica_search/js/obiba-mica-search-common.js
drupal/modules/obiba_mica/obiba_mica_search/js/obiba-mica-search-href.js

Also, made sure enpty queries are not in the URL

MK-242 - added the missing part to the range value

---

drupal/modules/obiba_mica/obiba_mica_search/js/obiba-mica-search-common.js
drupal/modules/obiba_mica/obiba_mica_search/js/obiba-mica-search-coverage.js
drupal/modules/obiba_mica/obiba_mica_search/js/obiba-mica-search-href.js
drupal/modules/obiba_mica/obiba_mica_search/js/obiba-mica-search-query-renderer.js
drupal/modules/obiba_mica/obiba_mica_search/js/obiba-mica-search_collapse_deal.js
drupal/modules/obiba_mica/obiba_mica_search/js/obiba-mica-search_tab_deal.js
drupal/modules/obiba_mica/obiba_mica_search/obiba_mica_search.module
drupal/modules/obiba_mica/obiba_mica_search/templates/obiba_mica_search_coverage.tpl.php

search and coverage pages ajaxified

MK-233 ajaxify search page

---

drupal/modules/obiba_mica/obiba_mica_search/js/obiba-mica-search-href.js

fixed conflict with modal dialogs used by drupal admin toolbar

fix onhashchange event binding

---

drupal/modules/obiba_mica/obiba_mica_commons/includes/obiba_mica_commons_resource_paths.inc

This fix needs to extend to all URLs in the Drupal client.

MK-295 - ajaxified all URLs in the helper class

---

drupal/modules/obiba_mica/obiba_mica_study/obiba_mica_study-page-detail.inc
drupal/modules/obiba_mica/obiba_mica_study/templates/obiba_mica_study-detail.tpl.php

MLSTRM-266

---

drupal/modules/obiba_mica/obiba_mica_network/obiba_mica_network-page-detail.inc

Largeur des colonnes dans les Networks individuels

MLSTRM-272

---

drupal/modules/obiba_mica/obiba_mica_search/templates/obiba_mica_search_checkbox_term.tpl.php

Page de recherche: mettre le nom des pays au complet dans les facettes

MLSTRM-296

---

drupal/modules/obiba_mica/obiba_mica_search/obiba_mica_search.module

Add copyright notice under Harmonization potential

MLSTRM-294

---

drupal/themes/obiba_bootstrap/less/overrides.less

- Add copyright notice under Harmonization potential
- Page de recherche: mettre en noir l'écriture quand on commence à écrire dans un text box
- Page de recherche: mettre le nom des pays au complet dans les facettes

MLSTRM-294 + MLSTRM-295 + MLSTRM-296

---

drupal/modules/obiba_mica/obiba_mica_study/templates/obiba_mica_study-list-page-block.tpl.php
drupal/themes/obiba_bootstrap/css/obiba.css
drupal/themes/obiba_bootstrap/css/style.css

MLSTRM-306

---

drupal/modules/obiba_mica/obiba_mica_search/obiba_mica_search.module

MLSTRM-294 

---

drupal/modules/obiba_mica/obiba_mica.admin.inc
drupal/modules/obiba_mica/obiba_mica.variable.inc
drupal/modules/obiba_mica/obiba_mica_dataset/templates/obiba_mica_dataset-detail.tpl.php
drupal/modules/obiba_mica/obiba_mica_dataset/templates/obiba_mica_dataset-list.tpl.php
drupal/modules/obiba_mica/obiba_mica_network/templates/obiba_mica_network-detail.tpl.php
drupal/modules/obiba_mica/obiba_mica_network/templates/obiba_mica_network-list.tpl.php
drupal/modules/obiba_mica/obiba_mica_study/templates/obiba_mica_study-dce-detail.tpl.php
drupal/modules/obiba_mica/obiba_mica_study/templates/obiba_mica_study-detail.tpl.php
drupal/modules/obiba_mica/obiba_mica_study/templates/obiba_mica_study-list-page.tpl.php

Also, made sure Coverage button visibilty responds to admin config setting

CPAC-28 - removed studies table

---

drupal/modules/obiba_mica/obiba_mica_dataset/includes/obiba_mica_variable_statistics.inc
drupal/modules/obiba_mica/obiba_mica_dataset/templates/obiba_mica_variable-detail.tpl.php

added a helper text to indicate thatthe result is the total of all studies

CPAC-30 - show sum of all stats for statistcal var's

---

drupal/modules/obiba_mica/obiba_mica_dataset/templates/obiba_mica_dataset-detail.tpl.php
drupal/modules/obiba_mica/obiba_mica_search/obiba_mica_search_charts.php

Customize Charts title
Description in markdown

Bug corrections

---

drupal/modules/obiba_mica/obiba_mica_dataset/templates/obiba_mica_variable-detail.tpl.php
drupal/modules/obiba_mica/obiba_mica_network/templates/obiba_mica_network-detail.tpl.php
drupal/modules/obiba_mica/obiba_mica_study/templates/obiba_mica_study-detail.tpl.php
drupal/themes/obiba_bootstrap/less/obiba.less

Description in markdown

---

drupal/modules/obiba_mica/obiba_mica_commons/includes/obiba_mica.inc

use session cookie when requesting mica

fix anonymous session cookie

---

drupal/themes/obiba_bootstrap/css/obiba.css
drupal/themes/obiba_bootstrap/less/obiba.less
drupal/themes/obiba_bootstrap/less/responsive_rules.less

CPAC-54 
Verify the layout on smaller devices

Responsive rules

---

drupal/modules/obiba_mica/obiba_mica_dataset/js/obiba_mica_dataset_variable_harmo_datatable_init.js
drupal/modules/obiba_mica/obiba_mica_dataset/js/obiba_mica_variable_harmo_algo_datatable_init.js

Hid the searchbox and the info parts

CPAC-92 - added an invalidate function to be used only when the table is parented under a hidden section

---

drupal/modules/obiba_mica/obiba_mica.module

(in information site configuration)

Made home introduction text editable as a slogan site

---

drupal/modules/obiba_mica/obiba_mica_commons/obiba_mica_commons.module
drupal/themes/obiba_bootstrap/css/obiba.css

in case of default charts configurations

Debug clickable charts in networks

---

Makefile
drupal/modules/obiba_mica/includes/obiba_mica.drush.inc

exp : drush obiba-progressbar-download 1.0.0
update make file to use this command

ProgressBar download command drush implementation

---

Makefile
drupal/themes/obiba_bootstrap/css/obiba.css
drupal/themes/obiba_bootstrap/css/style.css
drupal/themes/obiba_bootstrap/less/obiba.less

Page de recherche: mettre en noir l'écriture quand on commence à écrire dans un text box

MLSTRM-295

---

drupal/modules/obiba_mica/obiba_mica_commons/includes/obiba_mica.inc
drupal/modules/obiba_mica/obiba_mica_commons/obiba_mica_commons.module
drupal/modules/obiba_mica/obiba_mica_search/js/obiba-mica-search-href.js
drupal/modules/obiba_mica/obiba_mica_search/obiba_mica_search.module
drupal/modules/obiba_mica/obiba_mica_search/templates/obiba_mica_search_search.tpl.php
drupal/themes/obiba_bootstrap/css/obiba.css
drupal/themes/obiba_bootstrap/less/obiba.less

Reverts obiba/mica-drupal7-client#622

Revert "MK-410"

---

Makefile
drupal/dev/bower.json
drupal/modules/obiba_mica/includes/obiba_mica.drush.inc
drupal/themes/obiba_bootstrap/css/obiba.css
drupal/themes/obiba_bootstrap/css/style.css
drupal/themes/obiba_bootstrap/less/bootstrap.less
drupal/themes/obiba_bootstrap/less/obiba.less
drupal/themes/obiba_bootstrap/template.php
drupal/themes/obiba_bootstrap/templates/system/page--user.tpl.php
drupal/themes/obiba_bootstrap/templates/system/page.tpl.php
drupal/themes/obiba_bootstrap/templates/user-login.tpl.php
drupal/themes/obiba_bootstrap/templates/user-pass.tpl.php
drupal/themes/obiba_bootstrap/templates/user-register-form.tpl.php

Change templates registration login user
Add reCaptcha module to makeFile

MK-422/AGATE-39

---

drupal/modules/obiba_mica/obiba_main_app_angular/js/app/1-app.js
drupal/modules/obiba_mica/obiba_main_app_angular/obiba_main_app_angular.module

DataAccess

---

drupal/modules/obiba_mica/obiba_main_app_angular/js/app/app.js
drupal/modules/obiba_mica/obiba_main_app_angular/obiba_main_app_angular.module
drupal/modules/obiba_mica/obiba_mica_data_access_request/includes/obiba_mica_data_access_resources.inc
drupal/modules/obiba_mica/obiba_mica_data_access_request/js/app/data-access-request-controller.js
drupal/modules/obiba_mica/obiba_mica_data_access_request/obiba_mica_data_access_request.module
drupal/modules/obiba_mica/obiba_mica_data_access_request/obiba_mica_data_access_request_service.inc

permission redirect to login page if unauthorized

DataAccessRequest

---

drupal/modules/obiba_mica/obiba_main_app_angular/obiba_main_app_angular.module
drupal/modules/obiba_mica/obiba_mica_data_access_request/obiba_mica_data_access_request.module

Bug in list data access

---

drupal/modules/obiba_mica/obiba_main_app_angular/i18n/en.json
drupal/modules/obiba_mica/obiba_main_app_angular/i18n/fr.json
drupal/modules/obiba_mica/obiba_mica_commons/obiba_mica_commons.module
drupal/modules/obiba_mica/obiba_mica_data_access_request/js/app/views/obiba_mica_data_access_request-form-page.tpl.php
drupal/modules/obiba_mica/obiba_mica_data_access_request/js/app/views/obiba_mica_data_access_request-view-page.tpl.php
drupal/modules/obiba_mica/obiba_mica_data_access_request/js/obiba_mica_data_access_request_datatable_init.js
drupal/modules/obiba_mica/obiba_mica_dataset/includes/obiba_mica_variable_statistics.inc
drupal/modules/obiba_mica/obiba_mica_dataset/obiba_mica_dataset-page-detail.inc
drupal/modules/obiba_mica/obiba_mica_dataset/obiba_mica_variable-page-detail.inc
drupal/modules/obiba_mica/obiba_mica_dataset/templates/obiba_mica_dataset-harmonization-table-legend.tpl.php
drupal/modules/obiba_mica/obiba_mica_dataset/templates/obiba_mica_variable-detail.tpl.php
drupal/themes/obiba_bootstrap/css/obiba.css
drupal/themes/obiba_bootstrap/less/obiba.less

Url link corrections

---

drupal/modules/obiba_mica/obiba_mica_data_access_request/includes/obiba_mica_data_access_request.inc
drupal/modules/obiba_mica/obiba_mica_data_access_request/js/obiba_mica_data_access_request_datatable_init.js
drupal/modules/obiba_mica/obiba_mica_data_access_request/obiba_mica_data_access_request.module
drupal/modules/obiba_mica/obiba_mica_data_access_request/templates/obiba_mica_data_access_request-list.tpl.php
drupal/modules/obiba_mica/obiba_mica_data_access_request/templates/obiba_mica_data_access_request-page-data-access.tpl.php

Hide new request button for DAO

---

composer.json

Drush download facilities

---

obiba_mica_study/templates/obiba_mica_study-population-content-detail.tpl.php

Fix Study display

---

obiba_mica.variable.inc
obiba_mica_content_pages.admin.inc
obiba_mica_network/templates/obiba_mica_network-detail.tpl.php

CPTP dans MR Cancer
L'entête sous laquelle se trouve CPTP devrait être "Harmonized Research Platforms" et non "Networks".

Mlstrm 331

---

includes/obiba_mica.drush.inc

drush download-mica-dependencies  must have 2 parameters (folder to install in and the branch in the repository)
drush download-mica-dependencies '' master -> download the branch master on the sites/all/libraries/

Update for script deployment

---

obiba_mica_angular_search/includes/obiba_mica_angular_search_resources.inc
obiba_mica_angular_search/obiba_mica_angular_search.module
obiba_mica_angular_search/obiba_mica_angular_search_services.inc
obiba_mica_app_angular/js/app/app.js

Angular Search setting Order parameters

---

obiba_mica_angular_search/includes/obiba_mica_angular_search_resources.inc
obiba_mica_app_angular/js/app/app.js

Modify the query params resources

Remove LocalizedStringService from AngularJs main app

---

obiba_mica_graphic/js/app/obiba-mica-graphic-controller.js
obiba_mica_graphic/js/app/obiba-mica-graphic.js
obiba_mica_graphic/js/app/views/graphic-main.tpl.php
obiba_mica_graphic/obiba_mica_graphic.admin.inc
obiba_mica_graphic/obiba_mica_graphic.module
obiba_mica_graphic/templates/obiba_mica_angular_app_biological_samples_charts.tpl.php
obiba_mica_graphic/templates/obiba_mica_angular_app_geo_charts.tpl.php
obiba_mica_graphic/templates/obiba_mica_angular_app_study_design_charts.tpl.php

Add table 
debug the rendering of chart

Graphic modules integration

---

obiba_mica_angular_search/obiba_mica_angular_search.module
obiba_mica_angular_search/obiba_mica_angular_search_services.inc
obiba_mica_commons/obiba_mica_commons.module

Settings enabled for both authenticated or anonymous users

Cache if drupal cache enabled

---

obiba_mica_angular_search/js/app/obiba-search.js
obiba_mica_angular_search/obiba_mica_angular_search.module
obiba_mica_graphic/obiba_mica_graphic.admin.inc
obiba_mica_graphic/obiba_mica_graphic.module
obiba_mica_graphic/obiba_mica_graphic.variable.inc
obiba_mica_network/obiba_mica_network-page-detail.inc
obiba_mica_network/templates/obiba_mica_network-detail.tpl.php

Add setting graphic settings color

---

obiba_mica.variable.inc
obiba_mica_app_angular/js/app/app.js
obiba_mica_app_angular/obiba_mica_app_angular.module
obiba_mica_repository/includes/obiba_mica_repository_resources.inc
obiba_mica_repository/obiba_mica_repository.module
obiba_mica_repository/obiba_mica_repository_services.inc
obiba_mica_search_pages.admin.inc

Reverts obiba/mica-drupal7#860

Revert "MK-658 ng-obiba-mica config"

---

obiba_mica_app_angular/i18n/en.json

MK-724 changed coverage button to nav

---

obiba_mica.info
obiba_mica.variable.inc
obiba_mica_search_pages.admin.inc

Remove devel From dependecies of Obiba_mica

Correct the description, query

---

obiba_mica.variable.inc
obiba_mica_app_angular/obiba_mica_app_angular.module
obiba_mica_search_pages.admin.inc

Search 2 website: Remove some search and grouby criteria

MLSTRM-337

---

obiba_mica_commons/includes/obiba_mica.inc
obiba_mica_commons/includes/obiba_mica_commons_resource_paths.inc
obiba_mica_commons/obiba_mica_commons.module
obiba_mica_dataset/templates/obiba_mica_dataset-list-page-block.tpl.php
obiba_mica_network/templates/obiba_mica_network-list-page-block.tpl.php
obiba_mica_study/templates/obiba_mica_study-list-page-block.tpl.php

Make cache life cycle be the same of drupal setting cache

---

obiba_mica.variable.inc
obiba_mica_content_pages.admin.inc
obiba_mica_dataset/js/obiba_mica_dataset_toggle_harmo_table.js
obiba_mica_dataset/obiba_mica_dataset.module
obiba_mica_study/templates/obiba_mica_study-list-page-block.tpl.php
obiba_mica_study/templates/obiba_mica_study-list-page.tpl.php

Debug Notification Warning in studies list page
Make it possible to config display hide count studies il list page
implementation  hook to override the csv harmonization table download

In dataset bug on show harmonization table

---

obiba_mica_app_angular/js/app/app.js

Format number depending local language

MLSTRM-362

---

composer.json

Take in mind to fix a required version on releasing the module

Use dev-master protos version in master branch

---

obiba_mica_network/templates/obiba_mica_network-detail.tpl.php

img-responsive for network details

MLSTRM-367 - A graphic is missing in both search and network pages

---

obiba_mica_network/templates/obiba_mica_network-detail.tpl.php
obiba_mica_study/templates/obiba_mica_study-detail.tpl.php

MK-865 - Manage images size for networks and studies logos

---

obiba_mica.variable.inc
obiba_mica_content_pages.admin.inc
obiba_mica_dataset/templates/obiba_mica_dataset-detail.tpl.php
obiba_mica_dataset/templates/obiba_mica_dataset-list.tpl.php
obiba_mica_network/templates/obiba_mica_network-detail.tpl.php
obiba_mica_network/templates/obiba_mica_network-list.tpl.php
obiba_mica_search_pages.admin.inc
obiba_mica_study/templates/obiba_mica_study-detail.tpl.php
obiba_mica_study/templates/obiba_mica_study-list-page.tpl.php

Add buttons to access the search page from network and study pages as in Mica Admin

MLSTRM-380

---

obiba_mica_commons/includes/obiba_mica_commons_taxonomy_resource.inc
obiba_mica_search_pages.admin.inc

Fix the disappeared checkbox titles
Fix truncated drag icon
Remove Mica_variable taxonomy from taxonomies figure admin table

MK-872 Fix

---

composer.json

Update Composer release

---

obiba_mica_dataset/templates/obiba_mica_dataset-detail.tpl.php
obiba_mica_dataset/templates/obiba_mica_variable-detail.tpl.php
obiba_mica_network/templates/obiba_mica_network-detail.tpl.php
obiba_mica_study/templates/obiba_mica_study-detail.tpl.php
obiba_mica_study/templates/obiba_mica_study-population-content-detail.tpl.php

Verifier la case de tous les titres

MLSTRM-398

---

obiba_mica_commons/obiba_mica_commons.module
obiba_mica_study/templates/obiba_mica_study-list-page-block.tpl.php

Put number format for all numbers in network pages and study pages

MLSTRM-401

---

obiba_mica_dataset/obiba_mica_dataset-page-detail.inc

Studies not displayed in Harmo dataset page

MLSTRM-403

---

obiba_mica.variable.inc
obiba_mica_commons/includes/obiba_mica_commons_resource_paths.inc
obiba_mica_commons/obiba_mica_commons.module
obiba_mica_research_project/includes/obiba_mica_research_project_resource.inc
obiba_mica_research_project/obiba_mica_research_project-detail-page.inc
obiba_mica_research_project/obiba_mica_research_project-page-list.inc
obiba_mica_research_project/obiba_mica_research_project.info
obiba_mica_research_project/obiba_mica_research_project.install
obiba_mica_research_project/obiba_mica_research_project.module
obiba_mica_research_project/obiba_mica_research_project_service.inc
obiba_mica_research_project/templates/obiba_mica_research_project-detail.tpl.php
obiba_mica_research_project/templates/obiba_mica_research_project-list-page-block.tpl.php
obiba_mica_research_project/templates/obiba_mica_research_project-list-page.tpl.php
obiba_mica_study/obiba_mica_study-page-list.inc

The approved project page will list the title and summary of all published projects.
The project details page is a simple page that lists the project's title, summary, researcher name and institution. There is also a link to the project's data access request.

MK-887 - added page that lists published projects

---

obiba_mica_commons/obiba_mica_commons.module
obiba_mica_network/obiba_mica_network-page-detail.inc
obiba_mica_network/templates/obiba_mica_network-detail.tpl.php
obiba_mica_persons/obiba_mica_persons.module
obiba_mica_research_project/obiba_mica_research_project.module
obiba_mica_research_project/templates/obiba_mica_research_project-detail.tpl.php
obiba_mica_research_project/templates/obiba_mica_research_project-list-page-authenticated-block.tpl.php
obiba_mica_research_project/templates/obiba_mica_research_project-list-page-block.tpl.php

Fixed some errors where the property was undefined in the network details page and moved the date format function in commons.

Network details and general fixes

---

obiba_mica_search_pages.admin.inc

Number of characters limitation on the search/coverage help text

MLSTRM-409

---

obiba_mica.variable.inc
obiba_mica_app_angular/obiba_mica_app_angular.module
obiba_mica_content_pages.admin.inc
obiba_mica_data_access_request/obiba_mica_data_access_request.module
obiba_mica_files/obiba_mica_files.module

Added title callback for Data Access Requests/My Data Access Requests.
Add configuration entry for 'My Data Access Requests' variable
Removed some menus from the configuration ui by changing their type to 'MENU_CALLBACK'.

CPAC-288 - changes in data access request sub menu structure

---

obiba_mica.variable.inc
obiba_mica_content_pages.admin.inc

The forms for Data access request page content and research project page content will appear only if their module is enabled.

CPAC-288 - add configuration form for research project variables

---

obiba_mica_app_angular/js/app/app.js
obiba_mica_commons/includes/obiba_mica_commons_resource_paths.inc
obiba_mica_data_access_request/js/app/views/obiba_mica_data_access_request-form-header.tpl.php
obiba_mica_data_access_request/js/app/views/obiba_mica_data_access_request-view-header.tpl.php
obiba_mica_data_access_request/templates/obiba_mica_data_access_request-research-project-list-page-block.tpl.php
obiba_mica_research_project/templates/obiba_mica_research_project-detail.tpl.php
obiba_mica_research_project/templates/obiba_mica_research_project-list-page-block.tpl.php

A fix was also made for the url for the variable, network, study, studyPopulations and dataset pages in search.

CPAC-294 - fix DAR and project links on the research project list page to take the current lang into account

---

obiba_mica_commons/obiba_mica_commons.module
obiba_mica_data_access_request/obiba_mica_data_access_request.module
obiba_mica_research_project/templates/obiba_mica_research_project-detail.tpl.php

debug data access request label in project detail page
TO cherry-pick to 7.x-4.x

debug data access request Menu settings

---

obiba_mica.variable.inc
obiba_mica_content_pages.admin.inc
obiba_mica_dataset/templates/obiba_mica_dataset-detail.tpl.php
obiba_mica_study/templates/obiba_mica_study-dce-detail.tpl.php
obiba_mica_study/templates/obiba_mica_study-detail.tpl.php
obiba_mica_study/templates/obiba_mica_study-list-page-block.tpl.php

for 'Target Number of Participants', 'Target Number of Participants with Samples' and 'Supplementary Information About Target Number of Participants'. (7.x-4.x)

MLSTRM-414 - configuaration string 

---

obiba_mica.variable.inc
obiba_mica_commons/includes/obiba_mica.inc
obiba_mica_dataset/templates/obiba_mica_dataset-detail.tpl.php
obiba_mica_network/templates/obiba_mica_network-detail.tpl.php
obiba_mica_network/templates/obiba_mica_network_detail_coverage.tpl.php
obiba_mica_repository/includes/obiba_mica_repository_resources.inc
obiba_mica_study/templates/obiba_mica_study-detail.tpl.php
obiba_mica_study/templates/obiba_mica_study_detail_coverage.tpl.php
obiba_mica_study/templates/obiba_mica_study_fixed_sidebar.tpl.php

Rename to Variable'S' Classification
fix bug cache : Doesn ot work: https://staging.maelstrom-research.org/mica/repository#/search?type=studies&query=study(exists(Mica_study.id))&display=list
Some fix must be reflected to master

MLSTRM-421

---

obiba_mica_study/templates/obiba_mica_study-population-content-detail.tpl.php

In Mica admin/Study/Population, all added fields (dynamic) are not displayed in Drupal
Health Status
Ethnic Origin
Participants from existing studies / Add Study

MLSTRM-425

---

includes/obiba_mica.drush.inc

E.g. _drush download-mica-dependencies --path=/tmp/my-folder --repo=master_

MK-1081 - Used name options for repository and root path.

---

obiba_mica_network/obiba_mica_network-page-detail.inc

Set format for participants number in network page

MLSTRM-426

---

obiba_mica_graphic/obiba_mica_graphic.module
obiba_mica_network/obiba_mica_network-page-detail.inc
obiba_mica_repository/obiba_mica_repository.module

In Summary statistics, geographical distribution, one country does not appear on the MAP
Fix bug : the client configuration to set a convenient color set doesn't work

MLSTRM-382

---

obiba_mica_graphic/obiba_mica_graphic.module

Elargir l'histogramme de variables sur toute la page d'un DataSchema

MLSTRM-430

---

obiba_mica_dataset/templates/obiba_mica_variable-detail.tpl.php

Typo >: Remove S to status details

MLSTRM-433

---

includes/obiba_mica.drush.inc
obiba_mica_study/obiba_mica_study.install

Study timeline bug if the drupal module "obiba-mica" is updated

MK-1121 7.x-5.x

---

obiba_mica_commons/obiba_mica_commons.module
obiba_mica_dataset/obiba_mica_dataset-page-detail.inc
obiba_mica_dataset/obiba_mica_variable-page-detail.inc
obiba_mica_dataset/templates/obiba_mica_variable-detail.tpl.php

Fix undetermined harmo status 
Fix notice bug on a harmo variable page
Remove popup tooltips from status

MK-1131 - Drupal corrections for the dataschema/variables pages

---

obiba_mica_dataset/obiba_mica_dataset-page-detail.inc

The fact is that some status may be a Typos error

MK-1144 - Empty status in Harmo table causes a navigation bug

---

obiba_mica.module
obiba_mica_commons/obiba_mica_commons.module
obiba_mica_dataset/obiba_mica_dataset-page-detail.inc
obiba_mica_study/obiba_mica_study-page-detail.inc

More effective way to pass localize object to correct  template using hook_preprocess()
All magic happen in obiba_mica_commons_mica_server_localisation($theme)
we don't need to pay attention to passe instantiated MicaLocalisation\MicaDrupalLocalization() in every call of theme() function
But we have to define list of themes that need localized Object in obiba_mica_commons_mica_server_localisation()

MK-1149 - Dataset page translation error in drupal

---

composer.json
obiba_mica.module
obiba_mica_commons/includes/obiba_mica_commons_autoload.inc

Enhance errors handler by logging catched errors

Fix deploy with make file Error

---

obiba_mica_study/templates/obiba_mica_study-detail.tpl.php

Also remove study_dto->networks field

MK-1178 - Error in drupal when a contact has no institution defined

---

bower.json

As long as we are on the master (dev)

Using master branch of obiba js lib (progress bar / time line  etc)

---

obiba_mica.install

(Must be update on each release)
Nightly deployment using drush to retrieve Js libreries

Make sure to download master js branch on master branch

---

obiba_mica_dataset/obiba_mica_dataset-page-list.inc
obiba_mica_network/obiba_mica_network-page-list.inc
obiba_mica_study/obiba_mica_study-page-list.inc

in pages list (studies, networks, datasets) (Error logs mail: SandBox Server Staging Maelstrom Error)

Fix Errors Bugs on ajax call

---

README.md
obiba_mica_app_angular/js/app/app.js
obiba_mica_dataset/obiba_mica_dataset-page-list.inc
obiba_mica_network/obiba_mica_network-page-detail.inc
obiba_mica_network/obiba_mica_network-page-list.inc
obiba_mica_persons/js/obiba_mica_persons_datatable_init.js
obiba_mica_study/obiba_mica_study-page-list.inc

Fix Bugs : can't open modal of detail contact in study/network pages
Fix bug : Members modal in network detail pages
cherry-pick : 85a2853329d19cb0531c61f6903f91a71f6187e7
completly remove LocalizedValues override

Prepare release 7.x-20.0

---

obiba_mica_dataset/includes/obiba_mica_dataset_resource.inc
obiba_mica_dataset/js/app/dataset-variable-crosstab-controller.js
obiba_mica_dataset/js/app/views/obiba_mica_dataset_variable_crosstab.tpl.php
obiba_mica_study/templates/obiba_mica_study-population-content-detail.tpl.php

Tested with a project called test using spss datasource found in Dev/SampleXTab.sav in ownClound.
Created a study and study-dataset using Dev/test-essai.json and Dev/ds-test-essai.json to use on mica-drupal

MK-1147 - fixes for detailed and percentage buttons and for privacy checks

---

obiba_mica.install
obiba_mica_study/js/obiba-mica-study-timeline.js

+ Force admin theme to be default drupal theme (The bootstrap theme is buggy in the admin mode)

Translate pop and dce title in timeline

---

bower.json
includes/obiba_mica.drush.inc
obiba_mica.install
obiba_mica_network/obiba_mica_network-page-detail.inc
obiba_mica_persons/js/obiba_mica_persons_datatable_init.js
obiba_mica_study/obiba_mica_study-page-detail.inc

- Network detail page
- Js person table list
Update Js lib release versions

Correct some regressions on the master branch

---

obiba_mica_graphic/js/app/obiba-mica-graphic-controller.js
obiba_mica_study/templates/obiba_mica_study-population-content-detail.tpl.php

also fix for function call with wrong name in a template page

MK-1259 - fix regex for ids with special characters

---

obiba_mica_dataset/obiba_mica_dataset-page-detail.inc

MK-1262 : Harmo dataset variables table is super slow to display

---

bower.json
includes/Obiba/ObibaMicaClient/MicaClient/DrupalMicaClient/DrupalMicaClientResource.php
includes/obiba_mica.drush.inc
obiba_mica_app_angular/obiba_mica_app_angular.module
obiba_mica_dataset/js/app/views/obiba_mica_dataset_variable_crosstab.tpl.php
obiba_mica_dataset/obiba_mica_dataset-page-detail.inc
obiba_mica_dataset/obiba_mica_variable-page-detail.inc
obiba_mica_files/includes/obiba_mica_files_resources.inc
obiba_mica_network/includes/obiba_mica_network_resource.inc
obiba_mica_network/obiba_mica_network-page-detail.inc
obiba_mica_network/obiba_mica_network-page-list.inc
obiba_mica_network/templates/obiba_mica_network-detail.tpl.php
obiba_mica_repository/includes/obiba_mica_repository_resources.inc
obiba_mica_research_project/obiba_mica_research_project-detail-page.inc
obiba_mica_study/includes/obiba_mica_study_resource.inc
obiba_mica_study/obiba_mica_study-page-detail.inc
obiba_mica_study/templates/obiba_mica_study-population-content-detail.tpl.php
obiba_mica_study/templates/obiba_mica_study_detail_datasets.tpl.php

Fix : 
Updtae Js libraries
MK-1270  Improve performance in the Search/Coverage
MK-1262  Harmo-dataset variables table is super slow to display
General population, specific population and selection criteria  field not displayed

Release 20.8

---

obiba_mica_network/obiba_mica_network-page-detail.inc

Notice error in pusblished network

---

bower.json
includes/obiba_mica.drush.inc
obiba_mica.install

Bower js version consistency

---

obiba_mica.admin.inc
obiba_mica.variable.inc
obiba_mica_commons/obiba_mica_commons.module

The plain text field not correctly rendered in drupal because of the xss filter

MK-1335 -The plain text field not correctly rendered in drupal because of the xss filter

---

obiba_mica_network/templates/obiba_mica_network-detail.tpl.php
obiba_mica_persons/obiba_mica_persons_service.inc
obiba_mica_study/templates/obiba_mica_study-detail.tpl.php

Have to be mica server translation

Typo on members type

---

obiba_mica_network/templates/obiba_mica_network-detail.tpl.php

Fix Membership typo sapce

---

obiba_mica_study/templates/obiba_mica_study-population-content-detail.tpl.php

Remove "Selection criteria" before pregnant women, twins, newborns

MLSTRM-447

---

obiba_mica.module
obiba_mica_commons/obiba_mica_commons.module
obiba_mica_dataset/includes/obiba_mica_dataset_resource.inc
obiba_mica_dataset/obiba_mica_dataset-page-detail.inc
obiba_mica_dataset/obiba_mica_dataset.install
obiba_mica_dataset/obiba_mica_dataset.module
obiba_mica_dataset/obiba_mica_variable-page-detail.inc
obiba_mica_study/includes/obiba_mica_study_resource.inc
obiba_mica_study/obiba_mica_study-page-detail.inc
obiba_mica_study/obiba_mica_study-page-list.inc
obiba_mica_study/obiba_mica_study.install
obiba_mica_study/obiba_mica_study.module
obiba_mica_study/obiba_mica_study_hamonization_study-detail.inc
obiba_mica_study/templates/obiba_mica_study-list-harmo-study-page-block.tpl.php

Fix Some Refactoring Issues
- Fix Some bugy path
- More coerente constant path
- In Harmonization studies list remove the target number of participants in the sort form
- Add redirect routine for old studies/datasets
- Add update routine on updating module to correct the titles of studies/datasets list page

MK-1434 : Fix Some Refactoring Issues

---

obiba_mica_network/obiba_mica_network.module

Resore missing Networks table in a Study page

MLSTRM-451

---

obiba_mica_lists/js/app/obiba-lists.js
obiba_mica_lists/obiba_mica_lists.module

Configuration Variables consistence
List facet network
Update branch specific field in request
Correct the sort in the rql
Remove the autocomple

custom widget

---

obiba_mica_dashboard/includes/obiba_mica_dashboard_resources.inc
obiba_mica_dashboard/obiba_mica_dashboard.info
obiba_mica_dashboard/templates/obiba_mica_dashboard.tpl.php

- MLSTRM-462
- Fix the dashboard display on the homepage
- Correct the obiba mica dashboard module informations
- Make sure to not crash home page if error on connect to server but log a message error to debug

MLSTRM-473

---

obiba_mica_dataset/obiba_mica_dataset.module

Omitted harmonizationTable because it is not shown.

MK-1627 - add required fields for studyTable summary

---

obiba_mica.constants.inc
obiba_mica.module
obiba_mica_commons/includes/obiba_mica_commons_resource_paths.inc
obiba_mica_dataset/includes/obiba_mica_dataset_resource.inc
obiba_mica_dataset/obiba_mica_dataset.module
obiba_mica_dataset/templates/obiba_mica_dataset-detail.tpl.php
obiba_mica_network/obiba_mica_network-page-detail.inc
obiba_mica_network/templates/obiba_mica_network-detail.tpl.php
obiba_mica_study/templates/study-detail/obiba_mica_study-detail.tpl.php
obiba_mica_study/templates/study-detail/obiba_mica_study_harmonization_study-detail.tpl.php
templates/obiba_mica_search_bouton.tpl.php

MLSTRM-487

---

obiba_mica_lists/obiba_mica_lists.module

Please do not close this, there are real fixes (number of studies label) and questioning (what's that chronological sort hack?).

Sort options modified

---

bower.json
obiba_mica_app_angular/js/app/app.js
obiba_mica_app_angular/obiba_mica_app_angular.module
obiba_mica_repository/js/app/obiba-search.js

Fix some translation bug in the search

---

obiba_mica_commons/obiba_mica_commons.module
obiba_mica_lists/obiba_mica_lists.module
obiba_mica_repository/js/app/obiba-search.js
obiba_mica_repository/obiba_mica_repository.module

Prepare the possibility to override the header taxonomy panel
Maelstrom want to " Display results" button instead of the (X) close panel

Overriding header taxonomy panel

---

obiba_mica_data_access_request/js/obiba_mica_data_access_request_users_list_datatable_init.js
obiba_mica_network/js/obiba_mica_network_networks_datatable_init.js
obiba_mica_network/js/obiba_mica_network_studies_datatable_init.js

Study pagination for IALSA networks disapeared

MLSTRM-501

---

obiba_mica.info
obiba_mica_analysis/includes/obiba_mica_analysis_resources.inc
obiba_mica_analysis/js/app/obiba-analysis.js
obiba_mica_analysis/js/app/views/obiba_mica_analysis_entities_count-view-header.tpl.php
obiba_mica_analysis/obiba_mica_analysis.info
obiba_mica_analysis/obiba_mica_analysis.install
obiba_mica_analysis/obiba_mica_analysis.module
obiba_mica_analysis/obiba_mica_analysis_services.inc
obiba_mica_analysis/templates/obiba_mica_analysis_main_app.tpl.php
obiba_mica_app_angular/js/app/app.js
obiba_mica_commons/includes/obiba_mica_commons_resource_paths.inc
obiba_mica_dataset/includes/obiba_mica_dataset_resource.inc
obiba_mica_dataset/obiba_mica_dataset-page-detail.inc
obiba_mica_dataset/obiba_mica_dataset.module
obiba_mica_dataset/obiba_mica_variable-page-detail.inc
obiba_mica_repository/js/app/obiba-search.js

MK-1796 obiba_mica_analysis module added

---

bower.json
obiba_mica_study/obiba_mica_study-page-detail.inc

Modal in time line (Study page) not working any more

MK-1863 : Master branche

---

obiba_mica_commons/includes/obiba_mica_commons_resource_paths.inc
obiba_mica_commons/obiba_mica_commons.module
obiba_mica_dataset/obiba_mica_dataset.module
obiba_mica_dataset/templates/obiba_mica_variable-detail.tpl.php
obiba_mica_study/includes/obiba_mica_study_resource.inc
obiba_mica_study/js/obiba-mica-study-timeline.js
obiba_mica_study/obiba_mica_study-page-detail.inc

Reverts obiba/mica-drupal7#1582

Revert "7.x 34.x"

---

bower.json

Update js lib

---

includes/obiba_mica.drush.inc

Update js lib version

---

obiba_mica_dataset/obiba_mica_dataset-page-detail.inc
obiba_mica_dataset/obiba_mica_dataset.variable.inc
obiba_mica_dataset/obiba_mica_dataset_admin_form.inc
obiba_mica_dataset/templates/obiba_mica_dataset-detail.tpl.php
obiba_mica_dataset/templates/obiba_mica_dataset-study-tables.tpl.php

Fix the configuration studies display in harmonization and collected dataset detail pages

The Study display option in Dataset detail page don't take effect

---

obiba_mica_lists/obiba_mica_lists.admin.inc
obiba_mica_lists/obiba_mica_lists.module
obiba_mica_lists/obiba_mica_lists.variable.inc

This is in combination with the result tab config settings.

Added options in Study listing page to show counts.

---

obiba_mica_study/obiba_mica_study.variable.inc
obiba_mica_study/obiba_mica_study_admin_form.inc
obiba_mica_study/templates/study-detail/obiba_mica_study-detail.tpl.php
obiba_mica_study/templates/study-detail/obiba_mica_study_harmonization_study-detail.tpl.php

Add config to display or not the study list in the harmo project detail page

Fix Display study with one population

---

obiba_mica_app_angular/js/app/app.js
obiba_mica_app_angular/js/app/http-auth-interceptor.js
obiba_mica_app_angular/obiba_mica_app_angular.module
obiba_mica_data_access_request/obiba_mica_data_access_request_service.inc
obiba_mica_sets/obiba_mica_sets.module

&& Fix unauthorised access to lists page

Consolidate returned error server messages in angular app context

---

obiba_mica_app_angular/js/app/app.js
obiba_mica_sets/includes/obiba_mica_sets_resources.inc
obiba_mica_sets/obiba_mica_sets.module
obiba_mica_sets/obiba_mica_sets_services.inc

resources to download opal views

---

obiba_mica_commons/obiba_mica_commons.module

ps: it don't affect the current branch

Update braach with OIDC fix warning

---

obiba_mica_study/templates/study-detail/obiba_mica_access_representative_modal.tpl.php
obiba_mica_study/templates/study-detail/obiba_mica_study-detail-access.tpl.php

Add title and university for study representative

---

obiba_mica_graphic/obiba_mica_graphic.module

#3772 + #3771
Add a column with percentage and totals for both percentage and number of studies. Title of new column - Percentage of Studies.

Percentage column

---

includes/Obiba/ObibaMicaClient/MicaClient/DrupalMicaClient/DrupalMicaClientQueryRqlBuilders.php
obiba_mica_dataset/obiba_mica_dataset-page-detail.inc
obiba_mica_graphic/obiba_mica_graphic.module
obiba_mica_network/obiba_mica_network-page-detail.inc

Areas of Information Network graph :Use number of Studies not variables on the Y-axis
Fix bug on Click Stacked bar search by dce

#3774 Areas of Information Network graph

---

obiba_mica_app_angular/js/app/app.js
obiba_mica_graphic/includes/obiba_mica_graphic_statistics_resources.inc
obiba_mica_graphic/js/app/obiba-mica-graphic-controller.js
obiba_mica_graphic/js/app/obiba-mica-graphic.js
obiba_mica_graphic/js/app/views/graphic-chart-block-container.tpl.php
obiba_mica_graphic/js/app/views/graphic-chart-container.tpl.php
obiba_mica_graphic/js/app/views/graphic-main.tpl.php
obiba_mica_graphic/obiba_mica_graphic.module
obiba_mica_graphic/templates/obiba_mica_angular_app_charts_countriesIso.tpl.php

Add new graph start Year
Refactoring some graphic configuration

#3775 New graph #1 - Start Year

---

obiba_mica_graphic/js/app/obiba-mica-graphic-controller.js
obiba_mica_graphic/obiba_mica_graphic.admin.inc
obiba_mica_graphic/obiba_mica_graphic.module
obiba_mica_graphic/obiba_mica_graphic.variable.inc
obiba_mica_network/obiba_mica_network-page-detail.inc
obiba_mica_network/obiba_mica_network.variable.inc
obiba_mica_network/obiba_mica_network_admin_form.inc
obiba_mica_repository/includes/obiba_mica_repository_resources.inc

- Include 0 values
- replace network graphic coverage with horizontal Barchart with terms instead vocabularies
- Make the network graphic coverage to chose between variables/studies coverage
- add no limit row for participant table
- add undetermined row for Start year table

Graphics chart :

---

includes/Obiba/ObibaMicaClient/MicaClient/DrupalMicaClient/DrupalMicaClientQueryRqlBuilders.php
obiba_mica_graphic/js/app/obiba-mica-graphic-controller.js
obiba_mica_graphic/obiba_mica_graphic.module
obiba_mica_network/obiba_mica_network-page-detail.inc
obiba_mica_network/templates/obiba_mica_network-detail.tpl.php

- Fix coverage display
- Fix click on coverage bar
- Fix click on graphics

Fix Output:

---

obiba_mica_graphic/js/app/obiba-mica-graphic-controller.js
obiba_mica_graphic/obiba_mica_graphic.module

Font of subcategories - not bold, larger have to add more spacing from bars

Fix Graphics:

---

obiba_mica_graphic/js/app/obiba-mica-graphic-controller.js
obiba_mica_study/obiba_mica_study-page-detail.inc

- x-axis is all messed up, shows up duplicated value ticks for small values
- Can't disable the harmonization study coverage graphic
- Margin graphic in coverage not correctly misapplied

Graphics Fix :

---

obiba_mica_graphic/obiba_mica_graphic.admin.inc
obiba_mica_graphic/obiba_mica_graphic.module
obiba_mica_graphic/obiba_mica_graphic.variable.inc

May centre values graphic tables directives by configuration

Graphic tables style configuration

---

obiba_mica_dataset/obiba_mica_dataset.install
obiba_mica_dataset/obiba_mica_dataset.module
obiba_mica_dataset/obiba_mica_dataset.variable.inc
obiba_mica_dataset/obiba_mica_dataset_admin_form.inc

Add the Config of the sort criteria of the datasets list in the study detail page

Dataset Sort Criteria in Study

---

obiba_mica_dataset/obiba_mica_dataset.module

Check for hide_var field in dataset info to hide variable info

Remove Config min var to display info in datasets

---

obiba_mica_commons/includes/obiba_mica_commons_resource_paths.inc
obiba_mica_dataset/includes/obiba_mica_dataset_resource.inc
obiba_mica_study/includes/obiba_mica_study_resource.inc

To be compatible with the new Mica server version as edition is under admin/ path

Fix the edit Document button
